name: Java CI with Gradle

on:
  push:
    branches: [ "1.20.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Give Permissions
      run: chmod +x ./gradlew
    
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build
      id: build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build publish
      env:
        SNAPSHOT: true
        ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.NEXUS_USER }}
        ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.NEXUS_PASSWORD }}
        
    - name: Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TheAurorian
        path: |
            build/libs/
